"""empty message

Revision ID: 74118622d1c9
Revises: 92111d26c31f
Create Date: 2018-11-15 14:21:14.904053

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import mysql

# revision identifiers, used by Alembic.
revision = '74118622d1c9'
down_revision = '92111d26c31f'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('user', sa.Column('permission', sa.Integer(), nullable=True))
    op.drop_column('user', 'pression')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('user', sa.Column('pression', mysql.INTEGER(display_width=11), autoincrement=False, nullable=True))
    op.drop_column('user', 'permission')
    # ### end Alembic commands ###
