"""empty message

Revision ID: 816ac88d8dad
Revises: 8eb6173bd569
Create Date: 2018-11-14 21:28:48.545416

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '816ac88d8dad'
down_revision = '8eb6173bd569'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index('email', table_name='user')
    op.create_unique_constraint(None, 'user', ['token'])
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'user', type_='unique')
    op.create_index('email', 'user', ['email'], unique=True)
    # ### end Alembic commands ###
